version: "3"
services:
  spark:
    container_name: spark
    build:
      dockerfile: Dockerfile
      context: .
    external_links:
      - postgres:pgsql
      - rabbitmq:localhost
    entrypoint: 
      - python3
      - -u
      - main.py
    network_mode:
      bridge
    depends_on:
      rabbitmq:
        condition: service_healthy

  resource-producer:
    container_name: resource-producer
    build:
      dockerfile: Dockerfile
      context: .
    external_links:
      - postgres:pgsql
      - rabbitmq:localhost
    entrypoint: 
      - python3
      - -u
      - sending_resource.py
    network_mode:
      bridge
    depends_on:
      rabbitmq:
        condition: service_healthy
      
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    ports: 
      - 5762:5672
      - 15672:15672
    network_mode:
      bridge
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 15s
      retries: 5
